# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
class Fixnum
  def pentagonal
    n = self
    pent = ((3*(n**2)) - n) / 2
    pent
  end
  def pentagonal?
    n = self
    test = (Math.sqrt(1.0 + (24.0 * n)) + 1.0) / 6.0
    return (test == test.to_i)
  end
  def triangle
  	n = self
  	tri = ((n**2)+ n) / 2
  	tri
  end
  def triangle?
  	n = self
  	test = (Math.sqrt(1.0+(8.0 * n)) - 1.0) / 2.0
  	return (test == test.to_i)
  end
  def hexagonal
  	n = self
  	hex = ((2*(n**2))-n)
  	hex
  end
  def hexagonal?
  	n = self
    test = (Math.sqrt(1.0 + (8.0 * n)) + 1.0) / 4.0
    return (test == test.to_i)
  end
end

n = 144
notFound = true
result = 0
while notFound
	triangle = n.hexagonal
	puts triangle
	if triangle.pentagonal? && triangle.triangle?
		result = triangle
		notFound=false
	end
	n+=1
end
puts triangle

6995211921253

